"""EGY-Sentinel AML — Data Loader

Loads the demo dataset (data/demo.csv) generated by
scripts/generate_demo_data.py. The file is a ~200-row PaySim-format
CSV with 5 planted money-laundering patterns for demo purposes.

Also provides a patterns cache so detection results are computed once
and reused across all endpoints — solving the disconnection between
the detectors (DS-2) and the case builder (AI-3).

To regenerate the demo data:
    python scripts/generate_demo_data.py
"""
import logging
from functools import lru_cache
from pathlib import Path
from typing import Any

import pandas as pd

logger = logging.getLogger(__name__)

# Primary: data/demo.csv (committed, ~200 rows, 5 planted patterns)
# Fallback: data/sample/paysim_30k.csv (legacy 30K sample, gitignored)
DEMO_PATH = Path(__file__).parent / "demo.csv"
LEGACY_SAMPLE_PATH = Path(__file__).parent / "sample" / "paysim_30k.csv"

# Patterns cache file — generated by running detect_all() on the demo data.
# This bridges DS-2 (detectors) and AI-3 (case builder). Without this file,
# the case builder's evidence.py can't look up which pattern was detected.
PATTERNS_CSV_PATH = Path(__file__).parent / "patterns.csv"


def load_sample() -> pd.DataFrame:
    """Load the demo transaction dataset.

    Tries data/demo.csv first (preferred). Falls back to the legacy
    30K sample if present. Raises FileNotFoundError if neither exists.

    Returns:
        pd.DataFrame with PaySim-format columns:
        step, type, amount, nameOrig, nameDest,
        oldbalanceOrg, newbalanceOrig, oldbalanceDest, newbalanceDest,
        isFraud, isFlaggedFraud
    """
    if DEMO_PATH.exists():
        df = pd.read_csv(DEMO_PATH)
        logger.info(f"Loaded {len(df)} rows from demo dataset ({DEMO_PATH.name})")
        return df

    if LEGACY_SAMPLE_PATH.exists():
        df = pd.read_csv(LEGACY_SAMPLE_PATH)
        logger.info(f"Loaded {len(df)} rows from legacy sample ({LEGACY_SAMPLE_PATH.name})")
        return df

    raise FileNotFoundError(
        f"No demo data found. Looked for:\n"
        f"  {DEMO_PATH}\n"
        f"  {LEGACY_SAMPLE_PATH}\n"
        f"Run: python scripts/generate_demo_data.py"
    )


def get_demo_stats() -> dict:
    """Return summary statistics about the loaded dataset.

    Useful for the dashboard KPI strip.
    """
    df = load_sample()
    return {
        "total_transactions": len(df),
        "fraud_transactions": int(df["isFraud"].sum()),
        "fraud_rate": float(df["isFraud"].mean()),
        "unique_accounts": int(df["nameOrig"].nunique() + df["nameDest"].nunique()),
        "total_amount": float(df["amount"].sum()),
        "step_range": [int(df["step"].min()), int(df["step"].max())],
        "transaction_types": df["type"].value_counts().to_dict(),
    }


# ---------------------------------------------------------------------------
# Patterns cache — bridges DS-2 (detectors) and AI-3 (case builder)
# ---------------------------------------------------------------------------

_patterns_cache: dict[str, list[dict[str, Any]]] | None = None


def _ensure_patterns_cache(df: pd.DataFrame | None = None) -> dict[str, list[dict[str, Any]]]:
    """Build (and cache) a mapping of account_id → list of detected patterns.

    This solves the disconnection between the pattern detectors (DS-2) and
    the case builder (AI-3). Previously, the case builder's evidence.py
    looked up patterns from data/patterns.csv, but nothing ever generated
    that file — so detection results never reached the case report.

    Now: this function runs detect_all() once, caches the result, and
    returns a lookup dict. The orchestrator uses it to assign the correct
    pattern_type to each case.

    Args:
        df: Optional DataFrame. If None, loads the demo data.

    Returns:
        Dict mapping account_id → list of pattern dicts (each with
        'detector', 'accounts', 'score_raw', 'evidence').
    """
    global _patterns_cache
    if _patterns_cache is not None:
        return _patterns_cache

    if df is None:
        try:
            df = load_sample()
        except FileNotFoundError:
            logger.warning("No demo data — patterns cache is empty")
            _patterns_cache = {}
            return _patterns_cache

    try:
        from egysentinel.graph.build import build_digraph
        from egysentinel.detect import detect_all

        G = build_digraph(df)
        patterns = detect_all(G)

        # Build account → patterns lookup
        cache: dict[str, list[dict[str, Any]]] = {}
        for p in patterns:
            for acc in p.get("accounts", []):
                cache.setdefault(acc, []).append(p)

        _patterns_cache = cache
        logger.info(f"Patterns cache built: {len(patterns)} patterns, {len(cache)} accounts")

        # Also write to data/patterns.csv for evidence.py to use
        _write_patterns_csv(patterns)

        return _patterns_cache

    except Exception as e:
        logger.warning(f"Pattern detection failed: {e}. Patterns cache is empty.")
        _patterns_cache = {}
        return _patterns_cache


def _write_patterns_csv(patterns: list[dict[str, Any]]) -> None:
    """Write detected patterns to data/patterns.csv for evidence.py to read.

    Columns: account_id, pattern_type, description, confidence
    This is the format evidence.py's load_patterns() expects.
    """
    rows = []
    for p in patterns:
        detector = p.get("detector", "unknown")
        score = p.get("score_raw", 0.0)
        evidence = p.get("evidence", {})
        description = (
            f"{detector} pattern"
            + (f" · {evidence.get('cycle_length', '')} accounts" if "cycle_length" in evidence else "")
            + (f" · {evidence.get('receiver_count', '')} receivers" if "receiver_count" in evidence else "")
            + (f" · density {evidence.get('density', '')}" if "density" in evidence else "")
        )
        for acc in p.get("accounts", []):
            rows.append({
                "account_id": acc,
                "pattern_type": detector,
                "description": description,
                "confidence": round(score, 3),
            })

    df = pd.DataFrame(rows, columns=["account_id", "pattern_type", "description", "confidence"])
    df.to_csv(PATTERNS_CSV_PATH, index=False)
    logger.info(f"Wrote {len(df)} pattern rows to {PATTERNS_CSV_PATH}")


def clear_patterns_cache() -> None:
    """Clear the in-memory patterns cache. Call when data changes."""
    global _patterns_cache
    _patterns_cache = None


if __name__ == "__main__":
    # Quick sanity check when run directly
    logging.basicConfig(level=logging.INFO)
    df = load_sample()
    print(f"\nLoaded {len(df)} rows")
    print(f"Columns: {list(df.columns)}")
    print(f"Fraud rate: {df['isFraud'].mean():.4%}")
    print(f"\nFirst 5 rows:")
    print(df.head())
