"""EGY-Sentinel AML — Data Loader

Loads the demo dataset (data/demo.csv) generated by
scripts/generate_demo_data.py. The file is a ~200-row PaySim-format
CSV with 5 planted money-laundering patterns for demo purposes.

To regenerate the demo data:
    python scripts/generate_demo_data.py
"""
import logging
from pathlib import Path

import pandas as pd

logger = logging.getLogger(__name__)

# Primary: data/demo.csv (committed, ~200 rows, 5 planted patterns)
# Fallback: data/sample/paysim_30k.csv (legacy 30K sample, gitignored)
DEMO_PATH = Path(__file__).parent / "demo.csv"
LEGACY_SAMPLE_PATH = Path(__file__).parent / "sample" / "paysim_30k.csv"


def load_sample() -> pd.DataFrame:
    """Load the demo transaction dataset.

    Tries data/demo.csv first (preferred). Falls back to the legacy
    30K sample if present. Raises FileNotFoundError if neither exists.

    Returns:
        pd.DataFrame with PaySim-format columns:
        step, type, amount, nameOrig, nameDest,
        oldbalanceOrg, newbalanceOrig, oldbalanceDest, newbalanceDest,
        isFraud, isFlaggedFraud
    """
    if DEMO_PATH.exists():
        df = pd.read_csv(DEMO_PATH)
        logger.info(f"Loaded {len(df)} rows from demo dataset ({DEMO_PATH.name})")
        return df

    if LEGACY_SAMPLE_PATH.exists():
        df = pd.read_csv(LEGACY_SAMPLE_PATH)
        logger.info(f"Loaded {len(df)} rows from legacy sample ({LEGACY_SAMPLE_PATH.name})")
        return df

    raise FileNotFoundError(
        f"No demo data found. Looked for:\n"
        f"  {DEMO_PATH}\n"
        f"  {LEGACY_SAMPLE_PATH}\n"
        f"Run: python scripts/generate_demo_data.py"
    )


def get_demo_stats() -> dict:
    """Return summary statistics about the loaded dataset.

    Useful for the dashboard KPI strip.
    """
    df = load_sample()
    return {
        "total_transactions": len(df),
        "fraud_transactions": int(df["isFraud"].sum()),
        "fraud_rate": float(df["isFraud"].mean()),
        "unique_accounts": int(df["nameOrig"].nunique() + df["nameDest"].nunique()),
        "total_amount": float(df["amount"].sum()),
        "step_range": [int(df["step"].min()), int(df["step"].max())],
        "transaction_types": df["type"].value_counts().to_dict(),
    }


if __name__ == "__main__":
    # Quick sanity check when run directly
    logging.basicConfig(level=logging.INFO)
    df = load_sample()
    print(f"\nLoaded {len(df)} rows")
    print(f"Columns: {list(df.columns)}")
    print(f"Fraud rate: {df['isFraud'].mean():.4%}")
    print(f"\nFirst 5 rows:")
    print(df.head())
